### ISSUE TITLE
How to resolve main fields

### ISSUE THREAD

**Issue by eps1lon** [arcanis/rollup-plugin-pnp-resolve#2]
As of right now this plugin cannot be used as a drop-in for rollup-plugin-node-resolve because it ignores mainfields. It was mentioned in https://github.com/webpack/enhanced-resolve/issues/162#issuecomment-475949807 that this should be done in a separate plugin but mainfields used throughout many packages to identify commonJS and ES module builds while extensions are rarely used to identify these.

Would you consider adding support for a `mainFields` option to this plugin? I would like to put together a pull request for this.

Right now I'm using this custom jest resolver

```js
/**
 * Uses the specified mainField with PnP resolution
 * @param {string} request
 * @param {string} mainField
 * @param {JestResolverOptions} resolverOptions
 */
function resolveMainField(request, mainField, resolverOptions) {
	const issuer = `${resolverOptions.basedir}/`;
	const location = pnp.resolveToUnqualified(request, issuer, {
		extensions: resolverOptions.extensions,
	});
	/* 
	 * intuitevly packageInformation points to @material-ui/core's package.json
	 * but it returns the workspace root 
	const locator = pnp.findPackageLocator(location);
	const packageInformation = pnp.getPackageInformation(locator); */
	const packageJson = fse.readJsonSync(
		path.resolve(location, './package.json'),
	);

	const resolution = path.resolve(location, packageJson[mainField]);
	return resolution;
}
```

Overall I feel like I'm missing something because this goes back to resolve-by-filesystem. Shouldn't this information be available via pnpapi?

**Comment by crubier** [comment]
Same problem here
