### ISSUE TITLE
Seems to not work in monorepo? (works without this plugin)

### ISSUE THREAD

**Issue by tunnckoCore** [arcanis/rollup-plugin-pnp-resolve#5]
I have a monorepo with 3 worktrees (`workspaces: modules/*, commands/*, presets/*`) and all of them are in ESM.

I have `build` script on all of them which is similar to what's seen in the Berry monorepo: `build: "run build:compile \"$(pwd)\""`, so running the `build:compile` from the root package.json. Which script is `PKG_PATH=\"$0\" rollup -c`.

I have this plugin installed and this rollup config

```js
import resolve from 'rollup-plugin-pnp-resolve';

export default {
  input: path.join(process.env.PKG_PATH, 'src/index.js'),
  output: [
    {
      file: path.join(process.env.PKG_PATH, 'dist/cjs/index.js'),
      format: 'cjs',
    },
    {
      file: path.join(process.env.PKG_PATH, 'dist/esm/index.js'),
      format: 'esm',
    }
  ],
  plugins: [
    resolve(),
  ],
};
```

When I run build (for all workspaces with `yarn workspaces foreach -ptv run build`) I got error that it cannot resolve the dependencies.

```
➤ YN0000: [@hela/sade]: /home/charlike/github/tunnckoCore/hela/modules/sade/src/index.js → modules/sade/dist/cjs/index.js, modules/sade/dist/esm/index.js...
➤ YN0000: [@hela/sade]: [!] Error: 'default' is not exported by .yarn/cache/mri-npm-1.1.4-d22a399f26-1.zip/node_modules/mri/lib/index.js
➤ YN0000: [@hela/sade]: https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
➤ YN0000: [@hela/sade]: modules/sade/src/index.js (3:7)
➤ YN0000: [@hela/sade]: 2: 
➤ YN0000: [@hela/sade]: 3: import mri from 'mri';
```

It obviously tries to get the dependency in wrong way `.yarn/cache/mri-npm-1.1.4-d22a399f26-1.zip/node_modules/mri/lib/index.js`

When I run rollup without config and from the terminal, from the monorepo root

```
rollup -i ./modules/sade/src/index.js -o bundle.js
```

it works...

**Comment by tunnckoCore** [comment]
It seems that we don't even need that plugin. Removing it, everything works properly. :ok_hand: :rocket:

**Comment by arcanis** [comment]
Oh nice! We've had `resolve` integration for some time now, but it never hit me that `rollup-plugin-commonjs` was using it as well 😀 So yep, it should work just fine without the PnP plugin 🎉

**Comment by tunnckoCore** [comment]
Cool :taco: 

One small side Q: any ideas how to make work the `prettier-vscode` with PnP? I currently disabled it because it just fails, can't resolve. Through `vscode-eslint` it works, through terminal too.

**Comment by arcanis** [comment]
I'm not too sure - for `vscode-eslint` we use PnPify to provide an integration that ESLint can use (cf [VSCode Support](https://next.yarnpkg.com/advanced/pnpify#vscode-support)), I guess the same would have to be done for prettier 🤔

**Comment by tunnckoCore** [comment]
Yup, I've seen that. I thought something similar should be done inside the `pnpify` too.
